#!/bin/bash

HOME=/root
TARGET=$HOME/local # SMAC will be installed there

# SMAC needs java
apt-get install -y default-jre


# Install SMAC
mkdir -p $TARGET

cd /tmp
wget http://www.cs.ubc.ca/labs/beta/Projects/SMAC/smac-v2.08.00-master-731.tar.gz
tar -xzvf smac-v2.08.00-master-731.tar.gz -C $TARGET
rm -f smac-v2.08.00-master-731.tar.gz 
echo 'export PATH=$PATH:'"$TARGET/smac-v2.08.00-master-731" >> $HOME/.bashrc

# Install PySMAC

apt-get install -y libfreetype6-dev libxft-dev libpng12-dev libpython-dev

pip install mpldatacursor
pip install git+https://github.com/sfalkner/pysmac.git

exit 0
